name: Build

on: [push]

env:
  FABRIC_VERSION: ${{ inputs.fabric-version }}
  GOPATH: ${{ github.workspace }}/src/test/fixture

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        java-version:
          - "8"
          - "11"
          - "17"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.checkout-ref }}
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin
          cache: maven
      - name: Integration tests
        run: |
          ./scripts/run-integration-tests.sh
          find -name "*.xml"
